version: '3'
services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - './src/:/var/www/html'
      - './build/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    volumes:
      - './src/:/var/www/html'
    restart: on-failure
    user: app:1000
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
    - 3306:3306
