controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    prefix: /api
    resource: '../../src/Controller/Api/'
    name_prefix: 'api_'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
